openapi: "3.0.2"
info:
  title: DreamScore API
  version: "0.0.1"
servers:
  - url: https:/api.dreamscore.com/v1
tags:
  - name: Players
    description: Operations related to the players
  - name: Transfers
    description: Operations related to the transfers
paths:
  /players/{player_id}:
    get:
      tags:
        - Players

  /players/{player_id}/profile:
    get:
      tags:
        - Players

  /players/{player_id}/statistic:
    get:
      tags:
        - Players

  /players/{player_id}/market:
    get:
      tags:
        - Players

  /players/{player_id}/transfer:
    get:
      tags:
        - Players

  /leagues/{league_id}/transfers:
    get:
      tags:
        - Transfers
      summary: Get all transfers
      parameters:
        - $ref: "#/components/parameters/leagueId"
      responses:
        "200":
          description: A list of transfers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/transfer"

    post:
      tags:
        - Transfers
      summary: Add transfer
      parameters:
        - $ref: "#/components/parameters/leagueId"
      requestBody:
        description: The details of the player and the price
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                playerId:
                  type: integer
                  format: int64
                  description: The ID of the player
                price:
                  type: number
                  format: float
                  description: The price of the player
      responses:
        "201":
          description: The transfer was added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: The ID of the transfer

  /leagues/{league_id}/transfers/{transfer_id}:
    get:
      tags:
        - Transfers
      summary: Get transfer details
      parameters:
        - $ref: "#/components/parameters/leagueId"
        - $ref: "#/components/parameters/transferId"
      responses:
        "200":
          description: The details of the transfer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transfer"

    patch:
      tags:
        - Transfers
      summary: Update transfer price
      parameters:
        - $ref: "#/components/parameters/leagueId"
        - $ref: "#/components/parameters/transferId"
      requestBody:
        description: The new price for the transfer
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                price:
                  type: number
                  format: float
                  description: The new price for the player
      responses:
        "204":
          description: The price was updated successfully

    delete:
      tags:
        - Transfers
      summary: Remove transfer
      parameters:
        - $ref: "#/components/parameters/leagueId"
        - $ref: "#/components/parameters/transferId"
      responses:
        "204":
          description: The transfer was removed successfully

  /leagues/{league_id}/transfers/{transfer_id}/user:
    get:
      tags:
        - Transfers
      summary: Get user who added the transfer
      parameters:
        - $ref: "#/components/parameters/leagueId"
        - $ref: "#/components/parameters/transferId"
      responses:
        "200":
          description: The user who added the transfer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transferUser"

  /leagues/{league_id}/transfers/{transfer_id}/offers:
    get:
      tags:
        - Transfers
      summary: Get all offers for a transfer
      parameters:
        - $ref: "#/components/parameters/leagueId"
        - $ref: "#/components/parameters/transferId"
      responses:
        "200":
          description: A list of offers for the transfer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/transferOffer"

    post:
      tags:
        - Transfers
      summary: Place offer
      operationId: placeOffer
      parameters:
        - $ref: "#/components/parameters/leagueId"
        - $ref: "#/components/parameters/transferId"
      requestBody:
        description: The details of the offer
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                price:
                  type: number
                  format: float
                  description: The price of the offer
      responses:
        "201":
          description: The offer was placed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: The ID of the offer

  /leagues/{league_id}/transfers/{transfer_id}/offers/{offer_id}:
    post:
      tags:
        - Transfers
      summary: Accept offer
      operationId: acceptOffer
      parameters:
        - $ref: "#/components/parameters/leagueId"
        - $ref: "#/components/parameters/transferId"
        - $ref: "#/components/parameters/offerId"
      responses:
        "204":
          description: The offer was accepted successfully

    patch:
      tags:
        - Transfers
      summary: Update offer
      operationId: updateOffer
      parameters:
        - $ref: "#/components/parameters/leagueId"
        - $ref: "#/components/parameters/transferId"
        - $ref: "#/components/parameters/offerId"
      requestBody:
        description: The new price for the offer
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                price:
                  type: number
                  format: float
                  description: The new price for the offer
      responses:
        "204":
          description: The price was updated successfully

    delete:
      tags:
        - Transfers
      summary: Decline offer
      operationId: declineOffer
      parameters:
        - $ref: "#/components/parameters/leagueId"
        - $ref: "#/components/parameters/transferId"
        - $ref: "#/components/parameters/offerId"
      responses:
        "204":
          description: The offer was declined successfully

components:
  parameters:
    leagueId:
      in: path
      name: league_id
      required: true
      schema:
        type: integer
        format: int64
        description: The ID of the league
    transferId:
      in: path
      name: transfer_id
      required: true
      schema:
        type: integer
        format: int64
        description: The ID of the transfer
    playerId:
      in: path
      name: player_id
      required: true
      schema:
        type: integer
        format: int64
        description: The ID of the player
    offerId:
      in: path
      name: offer_id
      required: true
      schema:
        type: integer
        format: int64
        description: The ID of the offer
  schemas:
    transfer:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The ID of the transfer
        price:
          type: number
          format: float
          description: The price of the transfer
        entryDateTime:
          type: string
          format: date-time
          description: The date the transfer was added
        exitDateTime:
          type: string
          format: date-time
          description: The date the transfer will be removed
        player:
          $ref: "#/components/schemas/transferPlayer"
        user:
          $ref: "#/components/schemas/transferUser"
        offers:
          type: array
          items:
            $ref: "#/components/schemas/transferOffer"
    transferPlayer:
      properties:
        id:
          type: integer
          format: int64
          description: The ID of the player
        firstName:
          type: string
          description: The first name of the player
        lastName:
          type: string
          description: The last name of the player
        portraitUrl:
          type: string
          format: uri
          description: The URL of the player's portrait
        status:
          type: integer
          format: int64
          description: The status of the player (0 - fit, 1 - injured, 2 - stricken)
        position:
          type: integer
          format: int64
          description: The position of the player (0 - goalkeeper - gk, 1 - defense - def, 2 - midfield - mf, 3 - forward - fwd)
        number:
          type: integer
          format: int64
          description: The number of the player
        totalPoints:
          type: integer
          format: int64
          description: The total points of the player
        averagePoints:
          type: number
          format: float
          description: The average points of the player
        marketValue:
          type: number
          format: float
          description: The market value of the player
        marketValueTrend:
          type: integer
          format: int64
          description: The market value trend of the player (0 - stable, 1 - up, 2 - down)
    transferOffer:
      properties:
        id:
          type: integer
          format: int64
          description: The ID of the offer
        price:
          type: number
          format: float
          description: The price of the offer
        placedDateTime:
          type: string
          format: date-time
          description: The date the offer was placed
        user:
          $ref: "#/components/schemas/transferUser"
    transferUser:
      properties:
        id:
          type: integer
          format: int64
          description: The ID of the user who placed the offer
        name:
          type: string
          description: The name of the user who placed the offer
        portraitUrl:
          type: string
          format: uri
          description: The URL of the user's portrait
