openapi: 3.0.0
info:
  title: Kickbase API
  version: 1.0.0
  description: API documentation for Kickbase application

servers:
  - url: https://api.kickbase.com

tags:
  - name: User
    description: Operations related to user authentication and information
  - name: League
    description: Operations related to league management and information
  - name: Feed and Chat
    description: Operations related to league feed and chat history
  - name: Player
    description: Operations related to player information and market
  - name: Lineup
    description: Operations related to managing user lineups
  - name: Live Match Day
    description: Operations related to live match day information
  - name: Competition
    description: Operations related to competition information
  - name: Gift
    description: Operations related to collecting and viewing gifts
  - name: Achievements
    description: Operations related to user achievements

paths:
  /user/login:
    post:
      summary: Logs in a user
      description: Logs in a user by email and password.
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: Successful login

  /user/resetpassword:
    post:
      summary: Reset user password
      description: Resets user password.
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                token:
                  type: string
              required:
                - password
                - token
      responses:
        "200":
          description: Password reset successful

  /leagues:
    get:
      summary: Get league information
      description: Retrieves information about leagues.
      tags:
        - League
      responses:
        "200":
          description: List of leagues

  /leagues/{league_id}/info:
    get:
      summary: Get specific league information
      description: Retrieves information about a specific league.
      tags:
        - League
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: League information

  /leagues/{league_id}/me:
    get:
      summary: Get user info for a league
      description: Retrieves user info for a league.
      tags:
        - League
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User info

  /leagues/{league_id}/users:
    get:
      summary: Get users in a league
      description: Retrieves users in a league.
      tags:
        - League
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of users

  /leagues/{league_id}/users/{user_id}/profile:
    get:
      summary: Get user profile
      description: Retrieves user profile.
      tags:
        - League
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
        - in: path
          name: user_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User profile

  /leagues/{league_id}/feed:
    get:
      summary: Get league feed
      description: Retrieves league feed.
      tags:
        - Feed and Chat
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: League feed

  /leagues/{league_id}/live/chat:
    get:
      summary: Get chat history
      description: Retrieves chat history.
      tags:
        - Feed and Chat
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Chat history

    post:
      summary: Post a message to chat
      description: Posts a message to the chat.
      tags:
        - Feed and Chat
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
              required:
                - message
      responses:
        "200":
          description: Message posted successfully

  /leagues/{league_id}/live:
    get:
      summary: Get live match day overview
      description: Retrieves live match day overview.
      tags:
        - Live Match Day
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Live match day overview

  /leagues/{league_id}/market:
    get:
      summary: Get market information
      description: Retrieves market information.
      tags:
        - Player
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Market information

  /leagues/{league_id}/market/{player_id}:
    put:
      summary: Update player price
      description: Updates player price or removes player from market.
      tags:
        - Player
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
        - in: path
          name: player_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                price:
                  type: integer
              required:
                - price
      responses:
        "200":
          description: Player price updated successfully

    delete:
      summary: Remove player from market
      description: Removes player from market.
      tags:
        - Player
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
        - in: path
          name: player_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Player removed from market successfully

  /leagues/{league_id}/market/{player_id}/offers:
    post:
      summary: Place offer on player
      description: Places an offer on a player.
      tags:
        - Player
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
        - in: path
          name: player_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                price:
                  type: integer
              required:
                - price
      responses:
        "200":
          description: Offer placed successfully

  /leagues/{league_id}/market/{player_id}/offers/{offer_id}:
    post:
      summary: Accept player offer
      description: Accepts an offer on a player.
      tags:
        - Player
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
        - in: path
          name: player_id
          required: true
          schema:
            type: string
        - in: path
          name: offer_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Offer accepted successfully

    delete:
      summary: Decline player offer
      description: Declines an offer on a player.
      tags:
        - Player
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
        - in: path
          name: player_id
          required: true
          schema:
            type: string
        - in: path
          name: offer_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Offer declined successfully

  /leagues/{league_id}/lineup:
    get:
      summary: Get lineup
      description: Retrieves lineup.
      tags:
        - Lineup
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User lineup

    post:
      summary: Set lineup
      description: Sets lineup.
      tags:
        - Lineup
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                players:
                  type: array
                  items:
                    type: string
              required:
                - players
      responses:
        "200":
          description: Lineup set successfully

  /leagues/{league_id}/live/matches/{match_id}:
    get:
      summary: Get match details
      description: Retrieves match details.
      tags:
        - Live Match Day
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
        - in: path
          name: match_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Match details

  /leagues/{league_id}/live/notlinedupplayers:
    get:
      summary: Get not lined up players
      description: Retrieves not lined up players.
      tags:
        - Live Match Day
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Not lined up players

  /leagues/{league_id}/live/players/{player_id}:
    get:
      summary: Get player history
      description: Retrieves player history.
      tags:
        - Live Match Day
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
        - in: path
          name: player_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Player history

  /leagues/{league_id}/live/top10:
    get:
      summary: Get top 10 players
      description: Retrieves top 10 players.
      tags:
        - Live Match Day
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Top 10 players

  /leagues/{league_id}/live/teams/{team_id}/players:
    get:
      summary: Get team players
      description: Retrieves team players.
      tags:
        - Live Match Day
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
        - in: path
          name: team_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Team players

  /leagues/{league_id}/live/teamranking:
    get:
      summary: Get team ranking
      description: Retrieves team ranking.
      tags:
        - Live Match Day
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Team ranking

  /competition/best:
    get:
      summary: Get top 25 players
      description: Retrieves top 25 players.
      tags:
        - Competition
      responses:
        "200":
          description: Top 25 players

  /competition/matches:
    get:
      summary: Get matches
      description: Retrieves matches.
      tags:
        - Competition
      responses:
        "200":
          description: Matches

  /competition/table:
    get:
      summary: Get competition table
      description: Retrieves competition table.
      tags:
        - Competition
      responses:
        "200":
          description: Competition table

  /competition/teams/{team_id}/players:
    get:
      summary: Get team players
      description: Retrieves team players.
      tags:
        - Competition
      parameters:
        - in: path
          name: team_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Team players

  /competition/search:
    get:
      summary: Search competition players
      description: Searches competition players.
      tags:
        - Competition
      parameters:
        - in: query
          name: query
          schema:
            type: string
      responses:
        "200":
          description: Competition players search results

  /leagues/{league_id}/collectgift:
    post:
      summary: Collect gift
      description: Collects gift.
      tags:
        - Gift
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Gift collected successfully

  /leagues/{league_id}/currentgift:
    get:
      summary: Get current gift
      description: Retrieves current gift.
      tags:
        - Gift
      parameters:
        - in: path
          name: league_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Current gift
  
  /user/achievements:
    get:
      summary: Get user achievements
      description: Retrieves user achievements.
      tags:
        - Achievements
      responses:
        "200":
          description: User achievements

  /user/refreshchattoken:
    get:
      summary: Refresh chat token
      description: Refreshes chat token.
      tags:
        - Chat
      responses:
        "200":
          description: Chat token refreshed successfully